package com.example.coursesapp;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.ListView;

public class Aftm2 extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_aftm2);
        String names[]={"1 B.Tech. (Aerospace Engineering)",
                "2 B.Tech. (Agricultural and Food Engineering)",
                "3 B.Tech. (Agricultural Engineering)",
                "4 B.Tech. (Agricultural Information Technology)",
                "5  B.Tech. (Apparel Production Management)",
                "6 B.Tech. (Applied Electronics and Instrumentation)",
                "7 B.Tech. (Applied Mechanics)",
                "8 B.Tech. (Architectural Engineering)",
                "9 B.Tech. (Automobile Engineering)",
                "10 B.Tech. (Automotive Design Engineering)",
                "11 B.Tech. (Avionics Engineering)",
                "12 B.Tech. (Biochemical Engineering)",
                "13 B.Tech. (Bioinformatics)",
                "14 B.Tech. (Biomedical Engineering)",
                "15 B.Tech. (Biomedical Instrumentation)",
                "16 B.Tech. (Bioprocess Technology)",
                "17 B.Tech. (Biotechnology and Biochemical Engineering)",
                "18 B.Tech. (Biotechnology)",
                "19 B.Tech. (Carpet and Textile Technology)",
                "20 B.Tech. (Ceramic Technology)",
                "21 B.Tech. (Ceramic and Cement Technology)",
                "22 B.Tech. (Chemical Engineering)",
                "23 B.Tech. (Chemical Science and Technology)",
                "24 B.Tech. (Civil Engineering)",
                "25 B.Tech. (Civil Infrastructure Engineering)",
                "26 B.Tech. (Cloud Computing & Virtualization Technology)",
                "27 B.Tech. (Computer and Information Science)",
                "28 B.Tech. (Computer Engineering)",
                "29 B.Tech. (Computer Science and Engineering)",
                "30 B.Tech. (Dairy Technology)",
                "31 B.Tech. (Electrical and Electronics Engineering)",
                "32 B.Tech. (Electrical Engineering)",
                "33 B.Tech. (Electronics and Communication Engineering)",
                "34 B.Tech. (Electronics and Instrumentation Engineering)",
                "35 B.Tech. (Electronics and Media Technology)",
                "36 B.Tech. (Electronics and Nanotechnology)",
                "37 B.Tech. (Electronics and Telecom Engineering)",
                "38 B.Tech. (Electronics Engineering)",
                "39 B.Tech. (Energy Engineering)",
                "40 B.Tech. (Energy Technology)",
                "41 B.Tech. (Engineering Physics)",
                "42 B.Tech. (Environmental Engineering)",
                "43 B.Tech. (Fashion and Lifestyle Design) (FLD)",
                "44 B.Tech. (Fashion Technology)",
                "45 B.Tech. (Food Process Engineering)",
                "46 B.Tech. (Food Science)",
                "47 B.Tech. (Food Technology)",
                "48 B.Tech. (Footware Technology)",
                "49 B.Tech. (Genetic Engineering)",
                "50 B.Tech. (Geo Informatics Engineering)",
                "51 B.Tech. (Geo Sciences Engineering)",
                "52 B.Tech. (Hons.) (Electrical and Electronics Engineering)",
                "53 B.Tech. (Hons.) (Industrial and Production Engineering)",
                "54 B.Tech. (Hons.) Mechanical Engineering",
                "55 B.Tech. (Hons.) Agricultural Engineering",
                "56 B.Tech. (Hons.) Automobile Engineering",
                "57 B.Tech. (Hons.) Biotechnology",
                "58 B.Tech. (Hons.) Chemical Engineering",
                "59 B.Tech. (Hons.) Civil Engineering",
                "60 B.Tech. (Hons.) Computer Science and Engineering",
                "61 B.Tech. (Hons.) Electrical Communication Engineering",
                "62 B.Tech. (Hons.) Petroleum Engineering",
                "63 B.Tech. (Humanities and Management)",
                "64 B.Tech. (Industrial and Production Engineering)",
                "65 B.Tech. (Industrial Biotechnology)",
                "66 B.Tech. (Industrial Engineering and Management)",
                "67 B.Tech. (Industrial Engineering)",
                "68 B.Tech. (Industrial Microbiology)",
                "69 B.Tech. (Information and Communication Technology)",
                "70 B.Tech. (Information Science and Engineering)",
                "71 B.Tech. (Information Technology)",
                "72 B.Tech. (Infrastructure Engineering)",
                "73 B.Tech. (Instrumentation and Control Engineering)",
                "74 B.Tech. (Instrumentation Engineering)",
                "75 B.Tech. (Leather Technology)",
                "76 B.Tech. (Mainframe Technology)",
                "77 B.Tech. (Manufacturing & Management)",
                "78 B.Tech. (Manufacturing Technology)",
                "79 B.Tech. (Marine Engineering)",
                "80 B.Tech. (Material Science Engineering)",
                "81 B.Tech. (Mathematics and Computing)",
                "82 B.Tech. (Mechanical Engineering)",
                "83 B.Tech. (Mechatronics Engineering)",
                "84 B.Tech. (Medical Electronics)",
                "85 B.Tech. (Metallurgical Engineering)",
                "86 B.Tech. (Metallurgy)",
                "87 B.Tech. (Mineral Engineering)",
                "88 B.Tech. (Mining Engineering)",
                "89 B.Tech. (Missile Technology)",
                "90 B.Tech. (Nanotechnology)",
                "91 B.Tech. (Naval Architecture and Ocean Engineering)",
                "92 B.Tech. (Nuclear Power Technology)",
                "93 B.Tech. (Nuclear Science & Engineering)",
                "94 B.Tech. (Oil & Gas Informatics)",
                "95 B.Tech. (Optics and Optoelectronics)",
                "96 B.Tech. (Packaging Technology)",
                "97 B.Tech. (Paint Technology)",
                "98 B.Tech. (Petrochemical Engineering)",
                "99 B.Tech. (Pharmaceutical Technology)",
                "100 B.Tech. (Physical Sciences)",
                "101 B.Tech. (Plastic Technology)",
                "102 B.Tech. (Polymer Engineering)",
                "103 B.Tech. (Polymer Technology)",
                "104 B.Tech. (Power Engineering)",
                "105 B.Tech. (Power System Engineering)",
                "106 B.Tech. (Printing Technology)",
                "107 B.Tech. (Production Engineering)",
                "108 B.Tech. (Robotics Engineering)",
                "109 B.Tech. (Rubber Technology)",
                "110 B.Tech. (Safety and Fire Engineering)",
                "111 B.Tech. (Silk Technology)",
                "112 B.Tech. (Software Engineering)",
                "113 B.Tech. (Space Technology)",
                "114 B.Tech. (Telecommunication Engineering)",
                "115 B.Tech. (Textile Chemistry)",
                "116 B.Tech. (Textile Engineering)",
                "117 B.Tech. (Urban & Regional Planning)",
                "118 B.Tech. (Water Resources Engineering)"};
        ListView ls=findViewById(R.id.lvm2);
        ArrayAdapter<String> arrayAdapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,names);
        ls.setAdapter(arrayAdapter);
    }
}